name: digitaltrustagent
favicon: null
layout_spectrum: 0.8017735031899065
typography_spectrum: 0.9956431936006993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5374114795122296
  lightness: 0.5831481120549142
  saturation: 0.25474954349920154
  rhythmicContrast: 0.22151067364029586
purpose: []
